apiVersion: batch/v1
kind: CronJob
metadata:
  name: allotr-metrics-cronjob
  namespace: openfaas-fn
spec:
  # Executes each minute
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            allotr-metrics-cronjob: cronjob
        spec:
          containers:
          - name: allotr-metrics-cronjob
            image: rafaelpernil/allotr-metrics-cronjob:production
            imagePullPolicy: Always
          restartPolicy: OnFailure
